# Generated by Django 6.0.2 on 2026-03-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
