# Generated by Django 6.0.2 on 2026-03-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Course',
            new_name='course',
        ),
    ]
